#api: uvicorn --port $PORT api:app --reload
krakend: echo ./etc/krakend.json | entr -nrz krakend run --config etc/krakend.json
primary: bin/litefs mount -config ./etc/primary.yml
secondary: bin/litefs mount -config ./etc/secondary.yml
